### ISSUE TITLE
Analyzer assembly is in `lib` folder too, which breaks blazor/wasm AOT compilation

### ISSUE THREAD

**Issue by radical** [excubo-ag/Generators.Blazor#2]
Reference: https://github.com/dotnet/runtime/issues/56556

See comment https://github.com/dotnet/runtime/issues/56556#issuecomment-889576263, and  https://github.com/dotnet/runtime/issues/56556#issuecomment-889585968 

Feel free to correct me, if my analysis is not correct.

**Comment by stefanloerwald** [comment]
Hi @radical,

The inclusion of the assembly reference is on purpose, as it includes required attributes. Generating those attributes as part of the source generator is inferior (discoverability, performance, correctness in project hierarchies), therefore we opted for including it as assembly, not just SG.

I think I understand the problem it causes and will work on a fix to resolve the issue @qinhuaihe is experiencing. If my idea works out, it shouldn't be too difficult.

BR
Stefan

**Comment by stefanloerwald** [comment]
Resolved through 2dc541d, released as version 1.14.0.
