### ISSUE TITLE
SetParametersAsync SourceGenerator Compatility

### ISSUE THREAD

**Issue by TorreyGarland** [excubo-ag/Generators.Blazor#4]
Is it still incompatible if using seperate code-behind files?

**Comment by stefanloerwald** [comment]
Hi @TorreyGarland,

To the best of my knowledge, there's no incompatibility with code-behind files and the SetParametersAsync SG. Simply add the `[Excubo.Generators.Blazor.GenerateSetParametersAsync]` attribute on your component (either in .razor, or in .cs) and the correct code will be generated.

Note that this is entirely separate to the fact that net6.0 breaks razor-based SGs (see https://github.com/excubo-ag/Generators.Blazor#project-settings). As long as the roslyn team doesn't implement sequencing of SGs, there's no way to use both and there's nothing library authors can do about it.

Hope that helps
Stefan

**Comment by TorreyGarland** [comment]
Yes, it does.  Thanks for looking into this.
